site_name: University of Baghdad Veterinary Medicine
site_url: https://example.com
theme:
  name: material
  palette:
    - scheme: slate
      primary: black
  features:
    - navigation.sections
    - navigation.expand

markdown_extensions:
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/openseadragon/4.1.0/openseadragon.min.js
  - javascripts/viewer.js

nav:
  - Home: index.md
  - Inflammation:
      - Gastritis: data/inflammation/gastritis.md
  - Organs:
      - Spleen: data/organs/spleen.md
